version: '3.8'

services:
  web:
    build: ./becoder_qualify
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./becoder_qualify/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=becoderuser
      - POSTGRES_PASSWORD=becoderpasswd
      - POSTGRES_DB=becoder_db

volumes:
  postgres_data:
