# Generated by Django 4.0.3 on 2022-04-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedd', models.DateTimeField(auto_now_add=True)),
                ('data', models.FloatField()),
                ('smartdevice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.smartdevice')),
            ],
        ),
    ]
