# Generated by Django 4.0.3 on 2022-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='timedd',
            field=models.DateTimeField(),
        ),
    ]
